build:
	gcc trunchole.c -o myexe
	
run:
	./myexe ${ARGS}
	
clean:
	rm myexe
	
help:
	@echo "make build -to compile program"
	@echo "make run ARGS=<Directory path> -to run exe file"
	@echo "make clean --to remove exe file
