build:
	gcc crt.c -o myexe
	
run:
	./myexe ${ARGS}
	
help:
	@echo " make build -compiles the program file\n make run ARGS=<Path> -runs the built file\n make clean -deletes the built file"
	
clean:
	rm myexe
