build:
	gcc hole.c -o myexe

run:
	./myexe ${ARGS}
	
clean:
	rm myexe

help:
	@echo "make build -to compile the program"
	@echo "make run ARGS=<file name> -to run the exe file"
	@echo "make clean -to delete exe file"
