build:
	gcc copyfile.c -o myexe
	
run:
	./myexe ${ARGS1} ${ARGS2}
	
clean:
	rm myexe

help:
	echo "make build/run/clean"
	
helprun:
	echo "make run ARGS1=<Source File Name> ARGS2=<Destination File Name>"
