build:
	gcc filemode.c -o myexe
	
run:
	./myexe ${ARGS} 

clean:
	rm myexe
	
help:
	@echo "make build -to compile the programand create exe file"
	@echo "make run ARGS=<filename> -to execute the program exe"
	@echo "make clean -to remove exe file "
